### PR TITLE
Build F* with sedlex 2.4

### LINKED ISSUE #2343: F* does not build with sedlex 2.4
Yesterday, sedlex 2.4 was released on the opam package repository. With that new version of sedlex, I tried to build F* master, but I failed. When doing `make`, here is what I got:

```
make -C src/ocaml-output
make[1]: Entering directory '/home/everest/FStar/src/ocaml-output'
...
[OCAMLBUILD]
cd ../../ && ocamlbuild -cflag -g -I src/ocaml-output -I src/basic/ml -I src/parser/ml -I src/fstar/ml -I src/extraction/ml -I src/prettyprint/ml -I src/tactics/ml -I src/tests/ml -I ulib/ml -j 4 -build-dir src/ocaml-output/_build -use-ocamlfind main.native FStar_Syntax_Syntax.inferred.mli
+ ocamlfind ocamlc -c -g -thread -package stdint -package compiler-libs -package compiler-libs.common -package menhirLib -package dynlink -package pprint -package sedlex -package yojson -package ppxlib -package process -package sedlex.ppx -package batteries -package zarith -package ppx_deriving.std -package ppx_deriving_yojson -I src/parser/ml -I ulib/ml -I src/ocaml-output -I src/tests/ml -I src/basic/ml -I src/tactics/ml -I src/extraction/ml -I src/fstar/ml -I src/prettyprint/ml -o src/parser/ml/FStar_Parser_LexFStar.cmo src/parser/ml/FStar_Parser_LexFStar.ml
File "_none_", line 1:
Error: Unbound value Sedlexing.__private__next_int
Command exited with code 2.
Compilation unsuccessful after building 113 targets (112 cached) in 00:00:01.
make[1]: *** [Makefile:119: _build/src/fstar/ml/main.native] Error 10
make[1]: Leaving directory '/home/everest/FStar/src/ocaml-output'
make: *** [Makefile:6: all] Error 2
```

Due to that failure, the people who released sedlex 2.4 had to put a `sedlex < 2.4` upper bound on the dependencies for the `fstar` opam package (ocaml/opam-repository@915bcf6f4f55f6a7f2d94c965472d1c3666c07e6); and I had to pin sedlex to 2.3 on Project Everest for `./everest opam` (project-everest/everest@74400736da5a36223fb414a699f91bfc283d0caa).

### PR DESCRIPTION
**Pull request by tahina-pro**
This PR fixes #2343: F* has long not built with sedlex 2.4.

As @toots pointed out at https://github.com/FStarLang/FStar/issues/2343#issuecomment-962492550 , we are actually "replacing" sedlex's `Sedlexing` module with our own `src/parser/ml/FStar_Sedlexing.ml`, namely by:
https://github.com/FStarLang/FStar/blob/2b830a415628bd3832f3774a8f8c551d13fd1e62/src/parser/ml/FStar_Parser_LexFStar.ml#L7

There, I noticed that `__private__next_int` was not defined in our `FStar_Sedlexing`, but the lexer implementation generated by sedlex 2.4 does use that function. So I add it in this PR.

With this PR, `docker build --pull --file .docker/opam.Dockerfile .` successfully builds a Docker image that installs sedlex 2.4, builds F* against it, and run all F* regression tests.

Thank you Romain for your insights!

### CODE REVIEW

**Comment by nikswamy** [comment]
thanks! this is great and solves some install brittleness that many people have reported.
